### ISSUE TITLE
Evaluation of word links

### ISSUE THREAD

**Issue by egpbos** [TICCLAT/ticclat#10]
We should build a test suite to answer our research questions using the TICCLAT database we will design. These questions, as we currently see it, are:

- Research question(s):
  + Given combinations of input to TICCLAT:
    * Only test corpus
    * INL lexicon + test corpus
    * INL lexicon + names + test corpus
    * etcetera
  + .. and given test corpus (DBNL; including time, place, etc metadata) divided into training (TICCL input) and validation sets
  + .. what is the effect on performance in OCR post correction tasks?
    * What is the effect of adding lexicons (with historical spelling variation)? How much does it help and in which cases (if any) does it decrease performance?
  + .. how does TICCLAT perform on lexical assessment tasks? "Is this a word?"
    * Expert subjects
    * Layman subjects
    * Either in context or in isolation

**Comment by egpbos** [comment]
From #1 we should get two ways of linking morphological variants:

1. Via grammatical rules as encoded in lexicons through grouping of words by lemma
2. Derived from TICCL by analysis of lexicons with expanded morphological variants

- Research question:
  + What is the effect on performance using the different linking ways?

**Comment by jvdzwaan** [comment]
Moved to team eyra planning board.
