### ISSUE TITLE
UTF8 encoding issues

### ISSUE THREAD

**Issue by egpbos** [TICCLAT/ticclat#11]
The [Groene Boekje notebook](https://github.com/TICCLAT/ticclat/blob/master/notebooks/ticclat_db_ingestion/groene_boekje.ipynb) illustrates issues with ingestion and retrieval of unicode encoded strings. We create the database with utf8mb4 encoding with

```mysql
CREATE DATABASE ticclat CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
```

However, I can't get the Groene Boekje UTF-8 data that I'm creating in the notebook to be properly ingested. See the notebook for a more thorough explanation.

We should look into what's the cause of this weirdness. I also looked into global MySQL configuration options, but so far haven't found the answer (also see report on this in notebook).

**Comment by jvdzwaan** [comment]
This refers to the 'original' groene boekje data, and for ticclat we are using a derived word list.
