### ISSUE TITLE
Redo the anahashing with new alphabet and confusion files

### ISSUE THREAD

**Issue by jvdzwaan** [TICCLAT/ticclat#18]
Data on ponyland:

```
[mreynaert@applejack:~]$ ls -l /vol/tensusers/mreynaert/TICCLAT/ALPH
total 1081420
-rw-r--r-- 1 mreynaert mreynaert        919 Jun  3 17:08 nld.aspell.dict.clip20.lc.LD3.charconfus.clip20.lc.chars
-rw-r--r-- 1 mreynaert m12gtreynaert 1107366706 Jun  3 17:10 nld.aspell.dict.clip20.lc.LD3.charconfus.clip20.ld3.charconfus
```

**Comment by egpbos** [comment]
This is taking incredibly long with the current implementation (commit 0c9f272). Running for 27 hours now.

**Comment by egpbos** [comment]
Since this is now the default and for #17 we are going to ingest everything from scratch, the anahashes will also be correctly regenerated in that ingestion run, so #17 will fix this.
