### ISSUE TITLE
Use case: find gendered variants of wordforms

### ISSUE THREAD

**Issue by jvdzwaan** [TICCLAT/ticclat#31]
After implementing visualizations of the basic wordform statistics, we are going to be working on finding and visualizing gendered variants of wordforms; e.g., steward/stewardess. Based on such a word pair, the database allows you retrieve word pairs that differ in the same way (e.g., host/hostess). The idea is to allow the user to search for word pairs and then visualize the results by showing word form frequencies over time and corpora/lexica, historical and morphological variants.

Additional features
* Be able to search for using a postfix (e.g., -ess) and/or using myqsl LIKE queries

**Comment by egpbos** [comment]
List of wordpairs collected in https://github.com/TICCLAT/ticclat/issues/38#issuecomment-507187940

**Comment by jvdzwaan** [comment]
Moved to team eyra planning board.
