### ISSUE TITLE
Adjust database schema to accept morphological variants.

### ISSUE THREAD

**Issue by Maartenvm** [TICCLAT/ticclat#35]
#23 related

- [x] Think of a new schema
- [x] Change code to generate DB
- [x] Document
- [x] make room for INL id's

**Comment by jvdzwaan** [comment]
It seems the pos tags should be in a separate table, as there seems to be no link between the wordforms paradigms and the pos tags:

```
{'morph_par': {'Z0001Y0001X0023W00000004V0001_HDU003': {'Z': '0001',
   'Y': '0001',
   'X': '0023',
   'W': '00000004',
   'V': '0001',
   'h': 'HDU',
   't': '003'},
  'Z0001Y0001X0022W00000101V0013_HDU011': {'Z': '0001',
   'Y': '0001',
   'X': '0022',
   'W': '00000101',
   'V': '0013',
   'h': 'HDU',
   't': '011'}},
 'dict_ids': ['MNW_08286_s',
  'MNW_08282_s',
  'MNW_08283_s',
  'MNW_08284_s',
  'MNW_08287_s',
  'WNT_M015579_s'],
 'pos': ['NUM', 'ART', 'PRN', 'ADJ', 'NOU-C'],
 'int_ids': ['INT_252671', 'INT_28854', 'INT_321512']}
```

In this example, the wordform is part of two paradigms and has 5 pos tags.

**Comment by egpbos** [comment]
This looks good to me, let's close.

**Comment by egpbos** [comment]
Sorry, too soon. Was branch issue#35 actually merged somewhere? Or is that no longer used and can it be deleted?

**Comment by jvdzwaan** [comment]
The issue#35 branch was merged. I have deleted it.
