### ISSUE TITLE
Find out what morphological variant pairs are relevant for the Male/Female visualization.

### ISSUE THREAD

**Issue by Maartenvm** [TICCLAT/ticclat#38]
Find variants for one suffix.
Explore additional suffixes.

**Comment by egpbos** [comment]
From our example use-case, relevant female suffixes would be -ster, -in, -egge, -esse, -es, -ei, -e. The question is with which front parts these words are formed (either just one or several, see e.g. "klappei" below) and how this evolves over time (which front parts have which suffixes and use of certain suffixes in total). Examples:

- waarzeg`ster` (male: waarzeg`ger`), leid`ster` (male: leid`er`), ma`a`k`ster` (male: mak`er`), ski`ester` (male: ski`ër`)
- boer`in` (male: boer), kat`tin` (Flemish regional form ([source ANW](http://anw.inl.nl/article/kattin)); male: kat`er`; cat; non-gendered species name: kat), `_`ap`in` (weird form that nobody uses; male and non-gendered species name: `a`ap), be`_`r`in` (less weird; male and non-gendered species name: be`e`r), sla`vin` (male: sla`af`)
- die`vegge` (male: die`f`)
- secretar`esse` (male: secretar`is`)
- klappei (interesting rather rare form; male: klapp`aard` or klapp`er`, see e.g. [WNT entry for klappei](http://gtb.ivdnt.org/iWDB/search?actie=article&wdb=WNT&id=M032976))
- biolo`_`g`e` (male: biolo`o`g), Engels`e` (male: Engels`man`)
- baron`es` (male: baron), kunstena`_`r`es` (male: kunstena`a`r)
