### ISSUE TITLE
Check why morphological variants are sometimes double (ingest?)

### ISSUE THREAD

**Issue by Tommos0** [TICCLAT/ticclat#47]
SELECT cnt, COUNT(cnt) as freq from (
  SELECT COUNT(paradigm_id) AS cnt
  FROM morphological_paradigms
  GROUP BY Z, Y, X, W, V, word_type_code, word_type_number, wordform_id
) AS cnt_table GROUP BY cnt;

cnt    freq
1    79950
2    556101
4    2

**Comment by jvdzwaan** [comment]
I think the morphological variants were indeed added twice (by accident). The code was updated to empty the morphological variants table before ingestion:

https://github.com/TICCLAT/ticclat/blob/063a6edd201d185f02aa41c29cc9a8ec77b1febc/ticclat/ingest/morph_par.py#L19

We should check whether this is still a problem in the new version of the database.

**Comment by egpbos** [comment]
The current `ticclat_test` database on the VM shows:

```mysql
mysql> SELECT cnt, COUNT(cnt) as freq from ( SELECT COUNT(paradigm_id) AS cnt FROM morphological_paradigms GROUP BY Z, Y, X, W, V, word_type_code, word_type_number, wordform_id ) AS cnt_table GROUP BY cnt;
+-----+--------+
| cnt | freq   |
+-----+--------+
|   1 |  24322 |
|   2 | 611729 |
|   4 |      2 |
+-----+--------+
3 rows in set (12.84 sec)
```

**Comment by egpbos** [comment]
Moved to Eyra-team board.

**Comment by jvdzwaan** [comment]
We using database `ticclat_fixed` now.

```
mysql> SELECT cnt, COUNT(cnt) as freq from ( SELECT COUNT(paradigm_id) AS cnt FROM morphological_paradigms GROUP BY Z, Y, X, W, V, word_type_code, word_type_number, wordform_id ) AS cnt_table GROUP BY cnt;
+-----+--------+
| cnt | freq   |
+-----+--------+
|   1 | 611720 |
|   2 |      2 |
+-----+--------+
2 rows in set (6.76 sec)
```

We should remove the databases we are not using anymore...
